# Application
spring.application.name=storebox
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/storebox
spring.datasource.username=postgres
spring.datasource.password=16161364
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.defer-datasource-initialization=true

# JWT
app.jwt.secret=your-256-bit-secret-make-sure-to-change-this-in-production
app.jwt.expiration=86400000 # 24 hours in milliseconds

# Logging
logging.level.org.springframework=INFO
logging.level.myproject.storebox=DEBUG
logging.level.org.springframework.security=DEBUG

# Validation
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# SQL initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
