spring:
  config:
    import: "optional:classpath:.env[.properties]"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
      platform: postgresql
      schema-locations: classpath:schema-postgresql.sql

websiteUrl: ${WEBSITE_URL}